= Jeremy Wong - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: VolunCHeer

---

== Overview

This project portfolio page aim to record my contributions to the VolunCHeer project.

Our team was asked to enhance a command line interface addressbook for our software engineering project.
We decided to morph it into a volunteer management system called VolunCHeer.

VolunCHeer is an open-sourced Command Line Interface (CLI) management application to help Volunteer Project managers
easily keep track of their ongoing projects, volunteers, and beneficiaries. We aim to help our target users alleviate the
hassle of managing multiple projects, beneficiaries, and volunteers in an efficient and effective manner.


My role was to implement a data extraction command, complemented by a mapping and sorting command.
The following sections illustrate these enhancements in more detail, as well as the relevant sections I have added to
the user and developer guides in relation to these enhancements.

== My Role
My main task was to implement a data extraction command, complemented by filtered sorting commands. The following sections
will help explain my work on the enhancements in greater detail, as well as the corresponding sections of the user and developer
guides.

== Summary of contributions

* *Major enhancement*: added a *Filtered Volunteer Export* feature
** What it does: This feauture allows the user to export a list of volunteers into a CSV file, after sorting the volunteers
by certain chosen criteria. The commands used include:

*** map volunteers: Assigns points to all volunteers based on given criteria.
*** sort volunteers: Sorts the list of volunteers in descending order based on the points from the map command.
*** export volunteers: Exports the chosen particulars of the selected number of volunteers to a CSV file.

** Justification: This feature dramatically improves the convenience of the product because:
*** Some projects might require a certain subset of volunteers. For example, teaching tuition to secondary school children would
naturally be more fitting for students who have already completed that phase of education. The map and sort commands were also used in
collaboration with team member Zhao Jun Ru (username: quinzzzzz) to help find the best volunteers to assign to projects.
*** Other co-workers might not have the VolunCHeer app installed, so this feature allows sharing in a more universal format.
*** Furthermore, the ability to choose which particulars to export allows the user to preserve the privacy of volunteers
by only sharing required information.

** Highlights: The map and export command required intensive and careful parsing in order to provide the functionality of
allowing any subset of the possible parameters. Exporting also required a custom function to fit the data into a CSV-readable format.

** Credits: The implementation of the order list is based on the code written for the person list in the Address Book
Level 4 made by SE-EDU initiative.


* *Code contributed*: All my work can be viewed
https://nuscs2113-ay1819s2.github.io/dashboard-beta/#search=articstranger&sort=displayName&since=2019-02-10&until=2019-04-14&timeframe=day&reverse=false&repoSort=true[here]

* *Other contributions*:

** Documentation:
*** Edited and updated the README https://github.com/cs2113-ay1819s2-t08-1/main/pull/8[#8]
*** Collated and formatted the User Guide: https://github.com/cs2113-ay1819s2-t08-1/main/pull/8[#8][#14]
** Reviewed teammates pull requests on Github
https://github.com/cs2113-ay1819s2-t08-1/main/pull/142[#142]
** Addressed critical issues on Github
https://github.com/cs2113-ay1819s2-t08-1/main/issues/124[#124]

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=BeneficiaryManagement]


== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=BeneficiaryManagement]

include::../DeveloperGuide.adoc[tag=BenefUseCases]
