= Nguyen Dang Huu - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: AddressBook - Level 4

---
=== Introduction

The purpose of this portfolio is to document and demonstrate my contribution to the project namely VolunCHeer.
The project was carried out in AY 18/19 Sem 2 in NUS and was contribute by a team of four including myself.

== Overview

VolunCHeer is an open-source desktop management application for Volunteer Managers to manage various projects,
 beneficiaries and volunteers.

== Terminology
* Volunteer: The volunteers who participate in volunteer organization such as NUS Community Service Club, NUS Vietnamese
Community's CIP Committee.

* Beneficiary: Organizations who benefit from volunteering activities such as Old Folk Home, Nursing Home, and
Orphanage.

* Project: Projects that are set for volunteers to participate and help the beneficiary.

* Volunteer Manager: The one who manages the arrangement of projects, assign volunteers and contact and associate
beneficiaries with projects. In this project portfolio, the Volunteer manager will be referred as the user.

== Role
I am the Lead Developer, ensuring the application are as free of bugs as possible, especially in the early stage
where test files are not updated. I am also the adviser for implementation of commands and bug fixes. I also handle
damage control when problems arise.

== Summary of contributions

* *Major enhancement*: added *Beneficiary management feature*
** What it does: Beneficiary Management feature allows the user to manage beneficiary, including:

*** add a beneficiary: to open a new record of a beneficiary.
*** edit a beneficiary: to edit an existing record of a beneficiary.
*** find a beneficiary by name: to help the user quickly navigate to the wanted beneficiary record.
*** list beneficiaries: to list all beneficiary records.
*** summarise beneficiaries' data: to enable the user to see most active beneficiary based on attached project list.

** Justification: The beneficiary management feature allows the dynamic of tracking beneficiary records for the
volunteer manager to revise, reuse every time a project initiation process starts, because it is likely that the
volunteer manager will have projects related to previous beneficiary and the application creates a good starting point
and efficiently save time in terms of searching beneficiary's details. Moreover, it also allows the volunteer manager
to do consideration on which beneficiary to come for in terms of funding based on the activeness measurement of
beneficiaries.

** Highlights: This enhancement affects existing commands, data structure and commands to be added in future. It
requires in-depth analysis of implementation alternatives. The implementation too was challenging as it required changes
to existing commands and it involves the synchronization with related Projects and storage files.

** Credits: The implementation of the order list is based on the code written for the person list in the Address Book
Level 4 made by SE-EDU initiative.

* *Major enhancement*: updated "Storage Management"
** What it does: Storage is ensured to capture any change the user chooses to make in the application and to reflect
them in the storage file. When the user reopens the application, these changes are correctly viewed or if the data is
corrupted, the application will prompt the user.

** Justification: The data storage is important because the main purpose of the application is to reserve these data.
Hence, storage management is essential for the application to work properly and serve its purposes.

** Highlights: This enhancement is quite challenging as correlation between projects and beneficiaries, and projects and
volunteers requires the checking of corruption in storage files (ie. duplication of a project assigning to multiple
beneficiary).

* *Minor enhancement*: quality control of synchronization of assigning beneficiary to project
https://github.com/cs2113-ay1819s2-t08-1/main[#61]

* *Minor enhancement*: UI update up to version 1.3
https://github.com/cs2113-ay1819s2-t08-1/main[#43]

* *Minor enhancement*: Bug reports and fixed
https://github.com/cs2113-ay1819s2-t08-1/main[#43]



* *Code contributed*: My code contribution can be viewed
https://nuscs2113-ay1819s2.github.io/dashboard-beta/#search=huu&sort=displayName&since=2019-02-10&until=2019-04-01&timeframe=day&reverse=false&groupSelect=groupByRepos&breakdown=false[here]


* *Other contributions*:

** Giving substantial comments on Github
** Enhancements to existing features:
*** PENDING: Allow the selection of volunteers into details (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=addBeneficiary]

include::../UserGuide.adoc[tag=editBeneficiary]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]
