= Zhu Hui - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: AddressBook - Level 4

---

== Overview

This project portfolio page serves to document my contributions to the VolunCHeer project.

VolunCHeer is an open-sourced Command Line Interface (CLI) management application designed for Volunteering Project Managers.
We aim to help our target users alleviate the haystack of managing multiple projects, beneficiaries, and volunteers
in an efficient and effective manner.

Team T08-1 consists of Zhao Junru, Nguyen Dang Huu, Jeremy Wong Kai Wen and myself. We are a group of friends who have experiences,
working with major volunteering organizations. We understand the challenges volunteering project managers faced when dealing with
multiple projects, beneficiaries and volunteers and thus, we created VolunCHeer to serve that need.

== Terminology
* Volunteer: The volunteers who participate in volunteer organization such as NUS Community Service Club, NUS Vietnamese
Community's CIP Committee.

* Beneficiary: Organizations who benefit from volunteering activities such as Old Folk Home, Nursing Home, and
Orphanage.

* Project: Projects that are set for volunteers to participate and help the beneficiary.

* Volunteering Project Manager: The one who manages the arrangement of projects, assign volunteers and contact and associate
beneficiaries with projects. In this project portfolio, the Volunteering Project Manager is mentioned as the user.

== Role
I am in charge of testing for VolunCHeer. If you found any bugs in VolunCHeer, please do not hesitate to https://github.com/cs2113-ay1819s2-t08-1/main/blob/master/docs/AboutUs.adoc[contact us] directly.

== Summary of contributions

* *Major enhancement*: Volunteer Feature
** What it does: It allows Project Manager to store the data of the volunteers and access specific data easily with a few simple commands.
** Justification: This feature is one of the basic building blocks of VolunCHeer. Having access to and being able to filter
thousands of volunteers' data in matter of seconds would allow project managers to plan their projects efficiently and effectively.

* *Major enhancement*: Password Feature
** What it does: It prompts for a password verification upon executing the application and prevent unauthorised users from using VolunCHeer.
** Justification: The data stored in VolunCHeer is important and confidential. I have implemented the password feature
because we are concerned about the security of our users and do not wish data stored in our program to be stolen.
** Highlights: A simple UI with a single password field is used to implement this feature as it is more user friendly
compared to using the command line interface.

* *Minor enhancement*: Exit Dialog Box
** What it does: It prompts the user for a confirmation message when exiting VolunCHeer. It allows the `exit` command to bypass the message.
** Justification: This feature prevents accidental termination of the program by the user or external program.

* *Code contributed*: [https://github.com/cs2113-ay1819s2-t08-1/main/tree/master/src/main/java/seedu/address/logic/command/volunteer.java[Volunteer]] [https://github.com/cs2113-ay1819s2-t08-1/main/tree/master/src/main/java/seedu/address/ui/ValidatePassword.java[Password]]
* *Other contributions*:

** UI interface:
*** Ensure that UI is running smoothly
** Enhancements to existing features:
*** PENDING: Allow the selection of volunteers into details (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42])

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

*Volunteer Class
include::../UserGuide.adoc[tag=volunteerfeature]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

*Password Feature
include::../DeveloperGuide.adoc[tag=PasswordFeature]
